=== UCLComputerScience/COMP0016_2020_21_Team25/services/src/main/resources/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Service",
    "description": "A RESTful service API defining its endpoint and how to parse its JSON response message",
    "type": "object",
    "properties": {
        "name": {
            "description": "The name of the service, used in error-reporting",
            "type": "string"
        },
        "description": {
            "description": "Description of the service for others viewing the schema",
            "type": "string"
        },
        "url": {
            "description": "The base URL of the API with no query parameters or dynamic, parameter-based endpoints",
            "type": "string",
            "minLength": 1
        },
        "endpoints": {
            "description": "Dynamic, parameter-based endpoints to insert into the URL",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "type": "string",
                        "minLength": 1
                    },
                    "default": {
                        "type": "string",
                        "minLength": 1
                    }
                },
                "required": [
                    "name"
                ],
                "additionalProperties": false
            }
        },
        "api-key": {
            "description": "API key required to access the endpoint (if necessary)",
            "type": [
                "string",
                "object"
            ],
            "oneOf": [
                {
                    "type": "string",
                    "minLength": 1
                },
                {
                    "type": "object",
                    "properties": {
                        "alias": {
                            "type": "string"
                        },
                        "value": {
                            "type": "string",
                            "minLength": 1
                        }
                    },
                    "required": [
                        "value"
                    ],
                    "additionalProperties": false
                }
            ]
        },
        "parameters": {
            "description": "Parameters, usually from user input, to insert into the URL query parameters",
            "type": "object",
            "items": {
                "type": ["string", "object"],
                "oneOf": [
                    {
                        "type": "string",
                        "minLength": 1
                    },
                    {
                        "type": "object",
                        "properties": {
                            "alias": {
                                "type": "string"
                            },
                            "default": {
                                "type": "string"
                            },
                            "required": {
                                "type": "boolean"
                            }
                        },
                        "additionalProperties": false
                    }
                ]
            }
        },
        "message": {
            "description": "Describes how to parse the JSON response object from the API",
            "type": "string"
        },
        "error_code_name": {
            "description": "Describes where in the JSON response object to find the HTTP status code, if applicable",
            "type": "string"
        },
        "error_messages": {
            "description": "Defines a set of error messages for different HTTP codes",
            "type": "object",
            "items": {
                "type": "string"
            }
        },
        "metadata": {
            "description": "Defines how to store any extra information returned which is unsuitable for natural language",
            "type": "object",
            "items": {
                "type": [
                    "string",
                    "object"
                ]
            }
        },
        "error_metadata": {
            "description": "Defines how to store any extra information from an error JSON response",
            "type": "object",
            "items": {
                "type": [
                    "string",
                    "object"
                ]
            }
        }
    },
    "required": [
        "url",
        "parameters",
        "message"
    ],
    "additionalProperties": false
}

=== UCLComputerScience/COMP0016_2020_21_Team25/Services/src/main/resources/news.json
{
  "url": "https://newsapi.org/v2/everything",
  "api-key": {
    "alias": "apiKey",
    "value": "ee68362d0c8d492b9f525e5bc0d3989b"
  },
  "parameters": {
    "query": {
      "alias": "q",
      "required": true
    },
    "language": {
      "default": "en"
    },
    "page": {
      "default": 1
    },
    "pageSize": {
      "default": 1
    }
  },
  "message": "Here's the closest match I could find out of {totalResults} results. The article, published by {articles[0].source.name}, is titled \"{articles[0].title}\" and is written by {articles[0].author}. {articles[0].description}. The full article can be found on the {articles[0].source.name} website. Would you like to go there now?",
  "metadata": {
    "articles[0].url": "url",
    "articles[0].urlToImage": "image"
  }
}

=== UCLComputerScience/COMP0016_2020_21_Team25/App/Services-API/src/main/resources/current-weather.json
{
  "url": "https://api.openweathermap.org/data/2.5/weather",
  "api-key": {
    "alias": "appid",
    "value": "a19ed1a7f194054f0458cb07ba18c0c3"
  },
  "parameters": {
    "city": {
      "alias": "q",
      "default": "london"
    },
    "language": {
      "alias": "lang",
      "default": "en",
      "required": false
    }
  },
  "message": "The weather in {name} today is {weather[0].description} with the temperature being {main.temp} degrees celsius but will probably feel like {main.feels_like} degrees celsius. The high will be {main.temp_max} degrees celsius and the low, {main.temp_min} degrees celsius.",
  "error_code_name": "cod",
  "error_messages": {
    "404": "Could not find ...",
    "default": "I'm sorry, I could not find any weather information."
  },
  "metadata": {
    "data": {
      "custom": true,
      "children": {
        "wind.speed": "wind_speed",
        "coord.lat": "latitude",
        "coord.lon": "longitude"
      }
    },
    "weather[0]": "basic_weather_data"
  }
}

=== UCLComputerScience/COMP0016_2020_21_Team25/Services/src/main/resources/book.json
{
  "url": "https://gutendex.com/books",
  "parameters": {
    "query": "search",
    "languages": "languages",
    "topic": "topic"
  },
  "message": "I've found a {results[0].subjects[0]} book called {results[0].title}, written by {results[0].authors[0].name}. Would you like me to read it to you?",
  "metadata": {
    "results[0].id": {
      "alias": "id"
    },
    "results[0].formats.image/jpeg": "cover",
    "results[0].formats.text/html; charset=utf-8": "html",
    "results[0].formats.text/plain; charset=utf-8": "plaintext",
    "results[0].formats.application/x-mobipocket-ebook": "ebook",
    "results[0].formats.application/epub+zip": "epub"
  }
}
